name: yuxin_mea
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - ipywidgets
  - jupyterlab
  - notebook
  - pandas
  - pre-commit
  - pytest
  - scipy
  - h5py
  - zarr
  - pyarrow
  - spikeinterface
  - pytorch::pytorch>=2.7.0
  - pytorch::torchvision
  - pytorch::torchaudio
#  - pytorch-cuda=12.8
  - pynvml
  - pip:
    - kilosort
