name: yuxin_mea
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - ipywidgets
  - jupyterlab
  - notebook
  - pandas
  - pre-commit
  - pytest
  - scipy
  - h5py
  - zarr
  - spikeinterface
  - pynvml
  - plotly
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - "torch==2.10.0+cu128"
    - "torchvision==0.25.0+cu128"
    - "torchaudio==2.10.0+cu128"
    - kilosort

