"""Durable store for **manual** single-unit curation.

Manual labels / merges / splits / removals are human effort, so they must
**survive a pipeline re-run**. ``analyzer_data`` and
``curation_data/…/auto_curation`` are both regenerated by their tasks, so manual
curation is written to a **separate, pipeline-independent tree**::

    <analysis_root>/manual_curation_data/<recording_key>/<rec_name>/<well_id>/manual_curation.json

Only the dashboard writes it; :class:`~yuxin_mea.tasks.manual_curation.ManualCurationTask`
reads it. Writes are atomic (tmp + ``os.replace``), mirroring
``provenance/sidecar.py``.

The file is a small superset of the SpikeInterface **curation-format v2** it maps
onto (``good/MUA/noise`` labels, ``merges``, ``splits``, ``removed``) plus notes
and a **sorting fingerprint** so stale labels (the sorting changed upstream) are
flagged rather than silently misapplied. :func:`to_si_curation_dict` produces the
clean SI dict the apply task validates with ``si.curation.validate_curation_dict``.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

SCHEMA = "yuxin_mea.manual_curation/1"
MANIFEST_NAME = "manual_curation.json"
STAGE_ROOT = "manual_curation_data"
QUALITY_OPTIONS = ["good", "MUA", "noise"]


# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
def manifest_path(
    analysis_root: Path | str, recording_key: str, rec_name: str, well_id: str
) -> Path:
    return (Path(analysis_root) / STAGE_ROOT / recording_key / rec_name
            / well_id / MANIFEST_NAME)


def locate_from_analyzer_dir(
    analysis_root: Path | str, analyzer_dir: Path | str
) -> tuple[str, str, str] | None:
    """Recover ``(recording_key, rec_name, well_id)`` from an ``…/analyzer`` dir.

    Layout is ``<analysis_root>/analyzer_data/<rk>/<rec_name>/<well_id>/analyzer``.
    Returns ``None`` when the dir is not under ``analyzer_data``.
    """
    try:
        rel = Path(analyzer_dir).parent.relative_to(
            Path(analysis_root) / "analyzer_data")
    except ValueError:
        return None
    parts = rel.parts
    if len(parts) < 3:
        return None
    recording_key = "/".join(parts[:-2])
    return recording_key, parts[-2], parts[-1]


# --------------------------------------------------------------------------- #
# Fingerprint (cheap staleness marker — stat only, no content read)
# --------------------------------------------------------------------------- #
def sorting_fingerprint(analyzer_dir: Path | str, unit_ids: list[int]) -> str:
    """Stable hash over the sorting's ``spikes.npy`` stat + unit_ids.

    Content-hashing the NAS file is deliberately avoided (slow); a re-sort
    rewrites ``spikes.npy`` (new mtime/size) and changes unit_ids, either of
    which busts the fingerprint.
    """
    spikes = Path(analyzer_dir) / "sorting" / "spikes.npy"
    try:
        st = spikes.stat()
        stat_part = f"{st.st_size}:{st.st_mtime_ns}"
    except OSError:
        stat_part = "missing"
    payload = f"{stat_part}|{sorted(int(u) for u in unit_ids)}"
    return hashlib.sha1(payload.encode()).hexdigest()[:16]


# --------------------------------------------------------------------------- #
# Manifest CRUD
# --------------------------------------------------------------------------- #
def default_manifest(
    recording_key: str, rec_name: str, well_id: str,
    unit_ids: list[int], fingerprint: str,
) -> dict[str, Any]:
    return {
        "_schema": SCHEMA,
        "recording_key": recording_key,
        "rec_name": rec_name,
        "well_id": well_id,
        "sorting_fingerprint": fingerprint,
        "unit_ids": [int(u) for u in unit_ids],
        "labels": {},          # {unit_id(str): "good"|"MUA"|"noise"}
        "notes": {},           # {unit_id(str): str}
        "merges": [],          # [[unit_id, ...], ...]
        "removed": [],         # [unit_id, ...]
        "splits": [],          # [{"unit_id": int, "feature": str, "threshold": float}]
        "updated_at": None,
    }


def load_manifest(path: Path | str) -> dict[str, Any] | None:
    """Read our manifest; ``None`` if missing / unreadable / not ours."""
    p = Path(path)
    try:
        with p.open() as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or data.get("_schema") != SCHEMA:
        return None
    return data


def save_manifest(path: Path | str, manifest: dict[str, Any]) -> Path:
    """Atomically write the manifest (tmp + ``os.replace``); stamps ``updated_at``."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    manifest = {**manifest, "_schema": SCHEMA,
                "updated_at": datetime.now(timezone.utc).isoformat()}
    fd, tmp = tempfile.mkstemp(dir=p.parent, prefix=".mc_tmp_", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(manifest, fh, indent=2)
            fh.write("\n")
        os.replace(tmp, p)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return p


def is_stale(manifest: dict[str, Any], fingerprint: str) -> bool:
    """True when the manifest was authored against a different sorting."""
    return bool(manifest.get("sorting_fingerprint")) and \
        manifest["sorting_fingerprint"] != fingerprint


# --------------------------------------------------------------------------- #
# Mutation helpers (pure — operate on a manifest dict, return a new one)
# --------------------------------------------------------------------------- #
def set_label(manifest: dict[str, Any], unit_id: int, label: str) -> dict[str, Any]:
    if label not in QUALITY_OPTIONS:
        raise ValueError(f"label must be one of {QUALITY_OPTIONS}, got {label!r}")
    m = _clone(manifest)
    m["labels"][str(int(unit_id))] = label
    return m


def set_note(manifest: dict[str, Any], unit_id: int, note: str) -> dict[str, Any]:
    m = _clone(manifest)
    key = str(int(unit_id))
    if note:
        m["notes"][key] = note
    else:
        m["notes"].pop(key, None)
    return m


def toggle_removed(manifest: dict[str, Any], unit_id: int) -> dict[str, Any]:
    m = _clone(manifest)
    uid = int(unit_id)
    removed = set(int(u) for u in m["removed"])
    removed ^= {uid}
    m["removed"] = sorted(removed)
    return m


def add_merge_group(manifest: dict[str, Any], unit_ids: list[int]) -> dict[str, Any]:
    """Record a merge of >=2 units, coalescing with any overlapping group."""
    group = set(int(u) for u in unit_ids)
    if len(group) < 2:
        return _clone(manifest)
    m = _clone(manifest)
    kept: list[list[int]] = []
    for g in m["merges"]:
        gs = set(int(u) for u in g)
        if gs & group:
            group |= gs  # overlapping merges coalesce
        else:
            kept.append(sorted(gs))
    kept.append(sorted(group))
    m["merges"] = sorted(kept)
    return m


def clear_merges_for(manifest: dict[str, Any], unit_id: int) -> dict[str, Any]:
    uid = int(unit_id)
    m = _clone(manifest)
    m["merges"] = [sorted(int(u) for u in g) for g in m["merges"]
                   if uid not in {int(u) for u in g}]
    return m


def set_split(
    manifest: dict[str, Any], unit_id: int, feature: str, threshold: float
) -> dict[str, Any]:
    """Record a 1-D feature-threshold split spec (indices resolved at apply time)."""
    m = _clone(manifest)
    uid = int(unit_id)
    m["splits"] = [s for s in m["splits"] if int(s["unit_id"]) != uid]
    m["splits"].append({"unit_id": uid, "feature": str(feature),
                        "threshold": float(threshold)})
    return m


def clear_split(manifest: dict[str, Any], unit_id: int) -> dict[str, Any]:
    uid = int(unit_id)
    m = _clone(manifest)
    m["splits"] = [s for s in m["splits"] if int(s["unit_id"]) != uid]
    return m


def _clone(manifest: dict[str, Any]) -> dict[str, Any]:
    return json.loads(json.dumps(manifest))


# --------------------------------------------------------------------------- #
# Export to SpikeInterface curation-format v2
# --------------------------------------------------------------------------- #
def to_si_curation_dict(
    manifest: dict[str, Any],
    unit_ids: list[int],
    split_indices: dict[int, list[list[int]]] | None = None,
) -> dict[str, Any]:
    """Build a valid SI curation-format-v2 dict from our manifest.

    - ``labels`` → ``manual_labels`` under the ``quality`` definition.
    - Units labelled ``noise`` are added to ``removed`` (convention).
    - ``merges`` → ``merges`` (list of ``{"unit_ids": [...]}``).
    - ``splits`` require per-spike indices (feature-resolved by the apply task and
      passed as ``split_indices``); split specs without indices are skipped.
    """
    ids = [int(u) for u in unit_ids]
    labels = manifest.get("labels", {})
    manual_labels = [
        {"unit_id": int(uid), "labels": {"quality": [lab]}}
        for uid, lab in labels.items() if int(uid) in ids
    ]
    removed = set(int(u) for u in manifest.get("removed", []))
    removed |= {int(uid) for uid, lab in labels.items()
                if lab == "noise" and int(uid) in ids}

    merges = [{"unit_ids": sorted(int(u) for u in g)}
              for g in manifest.get("merges", []) if len(g) >= 2]

    splits = []
    if split_indices:
        for uid, groups in split_indices.items():
            if int(uid) in ids and groups and len(groups) >= 2:
                splits.append({"unit_id": int(uid), "mode": "indices",
                               "indices": [list(map(int, g)) for g in groups]})

    curation: dict[str, Any] = {
        "format_version": "2",
        "unit_ids": ids,
        "label_definitions": {
            "quality": {"name": "quality", "label_options": QUALITY_OPTIONS,
                        "exclusive": True}
        },
        "manual_labels": manual_labels,
        "merges": merges,
        "removed": sorted(removed),
        "splits": splits,
    }
    return curation
